version: '3.4'

services:
  synchronization:
    image: ${DOCKER_REGISTRY-}synchronization:latest
    build:
      context: .
      dockerfile: Synchronization/Dockerfile
    volumes:
      - src:/var/tmp/srcFolder
      - dest:/var/tmp/destFolder
      - logs:/var/tmp/logs
      
volumes:
  src:
  dest:
  logs: