version: '3.4'

services:
  synchronization:
    image: ${DOCKER_REGISTRY-}synchronization
    build:
      context: .
      dockerfile: Synchronization/Dockerfile
    volumes:
      - src:/var/tmp/srcFolder
      - dest:/var/tmp/destFolder
      - logs:/var/tmp/logs

  synchronizationtests:
    image: ${DOCKER_REGISTRY-}synchronizationtests
    build:
      context: .
      dockerfile: SynchronizationTests/Dockerfile
     volumes:
      - src:/var/tmp/srcFolder
      - dest:/var/tmp/destFolder

volumes:
  src:
  dest:
  logs:

