version: '3.4'

services:
  synchronization:
    image: lgsduran/synchronization
    build:
      context: .
    volumes:
      - src:/var/tmp/srcFolder
      - dest:/var/tmp/destFolder
      - logs:/var/tmp/logs
      
volumes:
  src:
  dest:
  logs: