# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Set up test folders
      run: |
        sudo chmod +x ./SynchronizationTests/scripts/folders.sh
        sudo ./SynchronizationTests/scripts/folders.sh    
    - name: Test
      run: dotnet test SynchronizationTests/SynchronizationTests.csproj
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build image docker-compose
      run: docker-compose up -d
    - name: Tag and push the image
      run: |
        docker tag synchronization ${{ secrets.DOCKER_USERNAME }}/synchronization:latest
        docker push ${{ secrets.DOCKER_USERNAME }}/synchronization:latest
