# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - 
      uses: actions/checkout@v4
    - 
      name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - 
      name: Workaround to mount the test folders
      run: |
        sudo chmod +x scripts/folders.sh
        sudo ./scripts/folders.sh    
    - 
      name: Test the Solution
      run: dotnet test SynchronizationTests/SynchronizationTests.csproj
    - 
      name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - 
      name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    -
      name: Build and test
      uses: docker/build-push-action@v5
      with:
        context: .
        target: build
        load: true
    -
      name: Build and push
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        target: final
        tags: ${{ secrets.DOCKER_USERNAME }}/synchronization:latest
